version: '3.8'
services:
  db:
    image: postgres:12.5
    command: -c log_statement=all
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: counter