FROM confluentinc/cp-kafka-connect:5.4.3

RUN cd /usr/share/java && \
    curl -X GET https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.4.1.Final/debezium-connector-postgres-1.4.1.Final-plugin.tar.gz > deb.tar.gz && \
    tar -xf deb.tar.gz && \
    rm deb.tar.gz && \
    cd debezium-connector-postgres && \
    curl -X GET  https://repo1.maven.org/maven2/io/debezium/debezium-scripting/1.4.1.Final/debezium-scripting-1.4.1.Final.tar.gz > scripting.tar.gz && \
    tar -xf scripting.tar.gz && \
    rm scripting.tar.gz && \
    curl -X GET https://repo1.maven.org/maven2/org/codehaus/groovy/groovy/3.0.7/groovy-3.0.7.jar > groovy-3.0.7.jar && \
    curl -X GET https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-jsr223/3.0.7/groovy-jsr223-3.0.7.jar > groovy-jsr223-3.0.7.jar && \
    curl -X GET https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-json/3.0.7/groovy-json-3.0.7.jar > groovy-json-3.0.7.jar